[package]
name = "pgol"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
itertools = "0.14.0"
nom = "8.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
